# Generated by Django 3.1.2 on 2022-05-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='realty name')),
                ('address', models.CharField(max_length=500, verbose_name='realty location')),
                ('transaction', models.CharField(choices=[('RN', 'Rental'), ('SL', 'Sale')], default='RN', max_length=2, verbose_name='type of realty transaction')),
                ('realty_type', models.CharField(choices=[('OF', 'Office'), ('LP', 'Land plot'), ('WH', 'Warehouse'), ('RT', 'Retail'), ('CW', 'Coworking')], default='OF', max_length=2, verbose_name='realty type')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='publication date')),
            ],
            options={
                'verbose_name': 'Realty',
                'verbose_name_plural': 'Realties',
            },
        ),
    ]
