# Generated by Django 3.1.2 on 2022-05-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='transaction',
            field=models.CharField(choices=[('RN', 'Rental'), ('SL', 'Sale')], default='RN', max_length=2, verbose_name='transaction type'),
        ),
    ]
