# Generated by Django 3.1.2 on 2022-05-07 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20220506_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='name of realty type')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='name of transaction type')),
            ],
        ),
        migrations.AlterField(
            model_name='realty',
            name='address',
            field=models.TextField(verbose_name='realty location'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='realty_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.realtytype', verbose_name='realty type'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.transactiontype', verbose_name='transaction type'),
        ),
    ]
