# Generated by Django 3.1.2 on 2022-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_auto_20220509_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='pub_date',
            field=models.DateTimeField(verbose_name='publication date'),
        ),
    ]
