# Generated by Django 3.1.2 on 2022-05-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_auto_20220509_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='address',
            field=models.TextField(max_length=200, verbose_name='realty location'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='title',
            field=models.CharField(max_length=100, verbose_name='realty name'),
        ),
        migrations.AlterField(
            model_name='realtytype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='name of realty type'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='title',
            field=models.CharField(max_length=100, verbose_name='name of transaction type'),
        ),
    ]
